### ISSUE TITLE
ERROR:  relation "coastline" does not exist

### ISSUE THREAD

**Issue by suminb** [mapnik/Cascadenik#32]
When I try to compile an `.mml` file:

```
cascadenik-compile.py style.mml style.xml
```

I get the following error message:

```
output file: style.xml /home/sumin/maps/OSM-Solar
Traceback (most recent call last):
  File "/usr/local/bin/cascadenik-compile.py", line 100, in <module>
    sys.exit(main(layersfile, outputfile, **options.__dict__))
  File "/usr/local/bin/cascadenik-compile.py", line 33, in main
    cascadenik.load_map(mmap, src_file, dirname(realpath(dest_file)), **load_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cascadenik/__init__.py", line 90, in load_map
    compile(src_file, dirs, verbose, datasources_cfg=datasources_cfg, user_styles=user_styles, scale=scale).to_mapnik(map, dirs)
  File "/usr/local/lib/python2.7/dist-packages/cascadenik/output.py", line 86, in to_mapnik
    lay.datasource = layer.datasource.to_mapnik()
  File "/usr/local/lib/python2.7/dist-packages/cascadenik/output.py", line 155, in to_mapnik
    return mapnik.Datasource(**self.parameters)
  File "/usr/lib/pymodules/python2.7/mapnik/__init__.py", line 319, in Datasource
    return CreateDatasource(keywords)
RuntimeError: Postgis Plugin: PSQL error:
ERROR:  relation "coastline" does not exist
LINE 1: SELECT * FROM coastline LIMIT 0
                      ^
Full sql was: 'SELECT * FROM coastline LIMIT 0'
```

Does anyone have any clue?

**Comment by nvkelso** [comment]
You are missing a data file called coastline.

See:
http://metro.teczno.com/#coastline

Sent from my handsful device.

On Feb 14, 2013, at 2:26, Sumin Byeon notifications@github.com wrote:

When I try to compile an .mml file:

cascadenik-compile.py style.mml style.xml

I get the following error message:

output file: style.xml /home/sumin/maps/OSM-Solar
Traceback (most recent call last):
  File "/usr/local/bin/cascadenik-compile.py", line 100, in <module>
    sys.exit(main(layersfile, outputfile, **options.**dict**))
  File "/usr/local/bin/cascadenik-compile.py", line 33, in main
    cascadenik.load_map(mmap, src_file, dirname(realpath(dest_file)),
**load_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cascadenik/**init**.py",
line 90, in load_map
    compile(src_file, dirs, verbose, datasources_cfg=datasources_cfg,
user_styles=user_styles, scale=scale).to_mapnik(map, dirs)
  File "/usr/local/lib/python2.7/dist-packages/cascadenik/output.py",
line 86, in to_mapnik
    lay.datasource = layer.datasource.to_mapnik()
  File "/usr/local/lib/python2.7/dist-packages/cascadenik/output.py",
line 155, in to_mapnik
    return mapnik.Datasource(**self.parameters)
  File "/usr/lib/pymodules/python2.7/mapnik/**init**.py", line 319, in
Datasource
    return CreateDatasource(keywords)
RuntimeError: Postgis Plugin: PSQL error:
ERROR:  relation "coastline" does not exist
LINE 1: SELECT \* FROM coastline LIMIT 0
                      ^
Full sql was: 'SELECT \* FROM coastline LIMIT 0'

Does anyone have any clue?

—
Reply to this email directly or view it on
GitHubhttps://github.com/mapnik/Cascadenik/issues/32.

**Comment by suminb** [comment]
It was because I had a different table name for `coastline`.

Adjusting the following line in `style.mml`

```
<Parameter name="table">coastline</Parameter>
```

as follows

```
<Parameter name="table">processed_p</Parameter>
```

resolved the problem I had. Thanks for your help.
