### ISSUE TITLE
windows test failures in relative-paths branch

### ISSUE THREAD

**Issue by springmeyer** [mapnik/Cascadenik#7]
<pre>
Microsoft Windows XP [Version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

C:\Documents and Settings\xp_user>cd Desktop

C:\Documents and Settings\xp_user\Desktop>cd Cascadenik

C:\Documents and Settings\xp_user\Desktop\Cascadenik>python test.py
..................E..EE
Cascadenik debug: Warning, FontSets will be ignored as they are not yet supporte
d in Mapnik via Python...
.....E................................EEEEFEEE.FE...............................
...........................................................
======================================================================
ERROR: testCompile1 (__main__.CompileXMLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1754, in testCompile1
    cfg = tempfile.NamedTemporaryFile('w', delete=False)
TypeError: NamedTemporaryFile() got an unexpected keyword argument 'delete'

======================================================================
ERROR: testCompile4 (__main__.CompileXMLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2007, in testCompile4
    ms.to_mapnik(mmap, self.dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\output.p
y", line 65, in to_mapnik
    lay.datasource = layer.datasource.to_mapnik()
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\output.p
y", line 134, in to_mapnik
    return mapnik.Datasource(**self.parameters)
  File "C:\Program Files\Mapnik\python\2.5\site-packages\mapnik\__init__.py", li
ne 261, in Datasource
    return CreateDatasource(keywords)
RuntimeError: data/test does not exist

======================================================================
ERROR: testCompile5 (__main__.CompileXMLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2026, in testCompile5
    ms.to_mapnik(mmap, self.dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\output.p
y", line 65, in to_mapnik
    lay.datasource = layer.datasource.to_mapnik()
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\output.p
y", line 134, in to_mapnik
    return mapnik.Datasource(**self.parameters)
  File "C:\Program Files\Mapnik\python\2.5\site-packages\mapnik\__init__.py", li
ne 261, in Datasource
    return CreateDatasource(keywords)
RuntimeError: data/test does not exist

======================================================================
ERROR: testLocalDefaultsFromFile (__main__.DataSourcesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1602, in testLocalDefaultsFromFile
    cfg = tempfile.NamedTemporaryFile('w', delete=False)
TypeError: NamedTemporaryFile() got an unexpected keyword argument 'delete'

======================================================================
ERROR: testAbsolutePaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2297, in testAbsolutePaths
    map = compile(mml_path, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1446, in compile
    declarations = extract_declarations(map_el, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 622, in extract_declarations
    rulesets = style.stylesheet_rulesets(styles, is_merc_projection(map_el.get('
srs','')))
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\style.py
", line 862, in stylesheet_rulesets
    declaration['value'] = postprocess_value(declaration['value'], declaration['
property'], line, col)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\style.py
", line 1101, in postprocess_value
    raw = str(tokens[0][1])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xca' in position 37:
 ordinal not in range(128)

======================================================================
ERROR: testDistantPaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2261, in testDistantPaths
    map = compile(mml_path, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1533, in compile
    get_point_rules(layer_declarations, dirs)))
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1211, in get_point_rules
    and postprocess_symbolizer_image_file(str(values['point-file'].value), dirs)
 \
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1094, in postprocess_symbolizer_image_file
    img = Image.open(path)
  File "C:\Program Files\Mapnik\python\2.5\site-packages\PIL\Image.py", line 198
0, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file

======================================================================
ERROR: testDistantPaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2124, in tearDown
    shutil.rmtree(self.tmpdir1)
  File "C:\Python25\lib\shutil.py", line 180, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python25\lib\shutil.py", line 178, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: 'c:\\docume~1\\xp_user\\locals~1\\temp\\cascadenik-test
s1-pjlenf\\purple-point.png'

======================================================================
ERROR: testLocalLinkedSheetPaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2345, in testLocalLinkedSheetPaths
    map = compile(mml_path, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1490, in compile
    file_param = localize_shapefile(file_param, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1358, in localize_shapefile
    path = unzip_shapefile_into(path, dirs.cache)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1302, in unzip_shapefile_into
    zip_file = zipfile.ZipFile(zip_path)
  File "C:\Python25\lib\zipfile.py", line 339, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: 'c:\\docume~1\\xp_user\\locals~1\\
temp\\cascadenik-tests2-hoxxwa\\mission-points.zip'

======================================================================
ERROR: testReflexivePaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2392, in testReflexivePaths
    map = compile(mml_data, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1446, in compile
    declarations = extract_declarations(map_el, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 622, in extract_declarations
    rulesets = style.stylesheet_rulesets(styles, is_merc_projection(map_el.get('
srs','')))
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\style.py
", line 862, in stylesheet_rulesets
    declaration['value'] = postprocess_value(declaration['value'], declaration['
property'], line, col)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\style.py
", line 1101, in postprocess_value
    raw = str(tokens[0][1])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xca' in position 44:
 ordinal not in range(128)

======================================================================
ERROR: testRelativePaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2225, in testRelativePaths
    map = compile(mml_path, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1533, in compile
    get_point_rules(layer_declarations, dirs)))
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1211, in get_point_rules
    and postprocess_symbolizer_image_file(str(values['point-file'].value), dirs)
 \
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1094, in postprocess_symbolizer_image_file
    img = Image.open(path)
  File "C:\Program Files\Mapnik\python\2.5\site-packages\PIL\Image.py", line 198
0, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file

======================================================================
ERROR: testRelativePaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2124, in tearDown
    shutil.rmtree(self.tmpdir1)
  File "C:\Python25\lib\shutil.py", line 180, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python25\lib\shutil.py", line 178, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: 'c:\\docume~1\\xp_user\\locals~1\\temp\\cascadenik-test
s1-dzznwl\\purple-point.png'

======================================================================
ERROR: testSplitLinkedSheetPaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2361, in testSplitLinkedSheetPaths
    map = compile(mml_path, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1490, in compile
    file_param = localize_shapefile(file_param, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1358, in localize_shapefile
    path = unzip_shapefile_into(path, dirs.cache)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1302, in unzip_shapefile_into
    zip_file = zipfile.ZipFile(zip_path)
  File "C:\Python25\lib\zipfile.py", line 339, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: 'c:\\docume~1\\xp_user\\locals~1\\
temp\\cascadenik-tests2-iak37h\\mission-points.zip'

======================================================================
FAIL: testLocalizedPaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2156, in testLocalizedPaths
    assert not os.path.isabs(img_path)
AssertionError

======================================================================
FAIL: testRemotePaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2316, in testRemotePaths
    assert not os.path.isabs(img_path)
AssertionError

----------------------------------------------------------------------
Ran 160 tests in 16.093s

FAILED (failures=2, errors=12)

C:\Documents and Settings\xp_user\Desktop\Cascadenik>
</pre>

**Comment by migurski** [comment]
Seemingly fixed the tempfile.NamedTemporaryFile errors in 4b9d03.

**Comment by springmeyer** [comment]
great, I'll boot up windows to test.

**Comment by springmeyer** [comment]
ah, nm, the NamedTemporaryFile errors were simply a py25 issue. So, I simply confirmed this fixed worked to clear those on osx.

**Comment by migurski** [comment]
I think it's possible that posixpath module is our way out of these issues. I'm starting to make changes in 353237 and bd31ae to understand more.

**Comment by springmeyer** [comment]
new failures with HEAD (basically right back where we started before http://github.com/mapnik/Cascadenik/commit/f395b50cd9f9fcbdaf3ccea2c0336225fb6618a3:

<pre>
  File "test.py", line 1763, in doCompile1
    map = compile(s, self.dirs, **kwargs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1436, in compile
    expand_source_declarations(map_el, dirs, datasources_cfg)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 651, in expand_source_declarations
    ds = sources.DataSources(dirs.source, local_conf)
AttributeError: Directories instance has no attribute 'source'

======================================================================
ERROR: testCompile2 (__main__.CompileXMLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1832, in testCompile2
    map = compile(s, self.dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1436, in compile
    expand_source_declarations(map_el, dirs, datasources_cfg)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 651, in expand_source_declarations
    ds = sources.DataSources(dirs.source, local_conf)
AttributeError: Directories instance has no attribute 'source'

======================================================================
ERROR: testCompile4 (__main__.CompileXMLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2001, in testCompile4
    ms = compile(s, self.dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1436, in compile
    expand_source_declarations(map_el, dirs, datasources_cfg)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 651, in expand_source_declarations
    ds = sources.DataSources(dirs.source, local_conf)
AttributeError: Directories instance has no attribute 'source'

======================================================================
ERROR: testCompile5 (__main__.CompileXMLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2020, in testCompile5
    ms = compile(s, self.dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1436, in compile
    expand_source_declarations(map_el, dirs, datasources_cfg)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 651, in expand_source_declarations
    ds = sources.DataSources(dirs.source, local_conf)
AttributeError: Directories instance has no attribute 'source'

======================================================================
ERROR: testLocalDefaultsFromFile (__main__.DataSourcesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1608, in testLocalDefaultsFromFile
    dss = DataSources(__file__, cfgpath)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\sources.
py", line 26, in __init__
    self.set_local_cfg_data(urllib.urlopen(self.local_cfg_url).read().decode(com
pile.DEFAULT_ENCODING))
  File "C:\Python25\lib\urllib.py", line 82, in urlopen
    return opener.open(url)
  File "C:\Python25\lib\urllib.py", line 187, in open
    return self.open_unknown(fullurl, data)
  File "C:\Python25\lib\urllib.py", line 199, in open_unknown
    raise IOError, ('url error', 'unknown url type', type)
IOError: [Errno url error] unknown url type: 'c'

======================================================================
ERROR: testAbsolutePaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2271, in testAbsolutePaths
    mml_file = open(mml_path, 'w')
IOError: [Errno 2] No such file or directory: 'C:\\Documents and Settings\\xp_us
er\\Desktop\\Cascadenik/c:\\docume~1\\xp_user\\locals~1\\temp\\cascadenik-tests2
-t6scwc/style.mml'

======================================================================
ERROR: testDistantPaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2235, in testDistantPaths
    mml_file = open(mml_path, 'w')
IOError: [Errno 2] No such file or directory: 'C:\\Documents and Settings\\xp_us
er\\Desktop\\Cascadenik/c:\\docume~1\\xp_user\\locals~1\\temp\\cascadenik-tests2
-tiavfv/style.mml'

======================================================================
ERROR: testLocalLinkedSheetPaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2340, in testLocalLinkedSheetPaths
    map = compile(mml_path, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1433, in compile
    doc = ElementTree.parse(urllib.urlopen(src))
  File "C:\Python25\lib\urllib.py", line 82, in urlopen
    return opener.open(url)
  File "C:\Python25\lib\urllib.py", line 190, in open
    return getattr(self, name)(url)
  File "C:\Python25\lib\urllib.py", line 457, in open_file
    return self.open_ftp(url)
  File "C:\Python25\lib\urllib.py", line 514, in open_ftp
    host = socket.gethostbyname(host)
IOError: [Errno socket error] (11001, 'getaddrinfo failed')

======================================================================
ERROR: testLocalizedPaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2127, in testLocalizedPaths
    mml_file = open(mml_path, 'w')
IOError: [Errno 2] No such file or directory: 'C:\\Documents and Settings\\xp_us
er\\Desktop\\Cascadenik/c:\\docume~1\\xp_user\\locals~1\\temp\\cascadenik-tests1
-ymz_ws/style.mml'

======================================================================
ERROR: testReflexivePaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2387, in testReflexivePaths
    map = compile(mml_data, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1437, in compile
    declarations = extract_declarations(map_el, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 616, in extract_declarations
    rulesets = style.stylesheet_rulesets(styles, is_merc_projection(map_el.get('
srs','')))
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\style.py
", line 862, in stylesheet_rulesets
    declaration['value'] = postprocess_value(declaration['value'], declaration['
property'], line, col)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\style.py
", line 1101, in postprocess_value
    raw = str(tokens[0][1])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xca' in position 44:
 ordinal not in range(128)

======================================================================
ERROR: testRelativePaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2199, in testRelativePaths
    mml_file = open(mml_path, 'w')
IOError: [Errno 2] No such file or directory: 'C:\\Documents and Settings\\xp_us
er\\Desktop\\Cascadenik/c:\\docume~1\\xp_user\\locals~1\\temp\\cascadenik-tests1
-zbiso1/style.mml'

======================================================================
ERROR: testRemoteLinkedSheetPaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2324, in testRemoteLinkedSheetPaths
    map = compile(mml_href, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1481, in compile
    file_param = localize_shapefile(file_param, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1338, in localize_shapefile
    scheme, path = '', locally_cache_remote_file(shp_href, dirs.cache)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1037, in locally_cache_remote_file
    f = open(local_path, 'wb')
IOError: [Errno 2] No such file or directory: 'C:\\Documents and Settings\\xp_us
er\\Desktop\\Cascadenik/c:\\docume~1\\xp_user\\locals~1\\temp\\cascadenik-tests2
-vtf5si/mission-points-03e5ab63.zip'

======================================================================
ERROR: testRemotePaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2308, in testRemotePaths
    map = compile(mml_href, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1481, in compile
    file_param = localize_shapefile(file_param, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1338, in localize_shapefile
    scheme, path = '', locally_cache_remote_file(shp_href, dirs.cache)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1037, in locally_cache_remote_file
    f = open(local_path, 'wb')
IOError: [Errno 2] No such file or directory: 'C:\\Documents and Settings\\xp_us
er\\Desktop\\Cascadenik/c:\\docume~1\\xp_user\\locals~1\\temp\\cascadenik-tests2
-c7w5z8/mission-points-03e5ab63.zip'

======================================================================
ERROR: testSplitLinkedSheetPaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2356, in testSplitLinkedSheetPaths
    map = compile(mml_path, dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1433, in compile
    doc = ElementTree.parse(urllib.urlopen(src))
  File "C:\Python25\lib\urllib.py", line 82, in urlopen
    return opener.open(url)
  File "C:\Python25\lib\urllib.py", line 190, in open
    return getattr(self, name)(url)
  File "C:\Python25\lib\urllib.py", line 457, in open_file
    return self.open_ftp(url)
  File "C:\Python25\lib\urllib.py", line 514, in open_ftp
    host = socket.gethostbyname(host)
IOError: [Errno socket error] (11001, 'getaddrinfo failed')

======================================================================
ERROR: testSplitPaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2163, in testSplitPaths
    mml_file = open(mml_path, 'w')
IOError: [Errno 2] No such file or directory: 'C:\\Documents and Settings\\xp_us
er\\Desktop\\Cascadenik/c:\\docume~1\\xp_user\\locals~1\\temp\\cascadenik-tests1
-ljzjf6/style.mml'

======================================================================
ERROR: testStyleRules05 (__main__.StyleRuleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1044, in testStyleRules05
    shield_rule_groups = get_shield_rule_groups(declarations, self.dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1162, in get_shield_rule_groups
    and postprocess_symbolizer_image_file(str(values['shield-file'].value), dirs
) \
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1067, in postprocess_symbolizer_image_file
    file_href = urljoin(dirs.source.rstrip('/')+'/', file_href)
AttributeError: Directories instance has no attribute 'source'

======================================================================
ERROR: testStyleRules06 (__main__.StyleRuleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1112, in testStyleRules06
    shield_rule_groups = get_shield_rule_groups(declarations, self.dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1162, in get_shield_rule_groups
    and postprocess_symbolizer_image_file(str(values['shield-file'].value), dirs
) \
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1067, in postprocess_symbolizer_image_file
    file_href = urljoin(dirs.source.rstrip('/')+'/', file_href)
AttributeError: Directories instance has no attribute 'source'

======================================================================
ERROR: testStyleRules07 (__main__.StyleRuleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1187, in testStyleRules07
    point_rules = get_point_rules(declarations, self.dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1205, in get_point_rules
    and postprocess_symbolizer_image_file(str(values['point-file'].value), dirs)
 \
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1067, in postprocess_symbolizer_image_file
    file_href = urljoin(dirs.source.rstrip('/')+'/', file_href)
AttributeError: Directories instance has no attribute 'source'

======================================================================
ERROR: testStyleRules13 (__main__.StyleRuleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1491, in testStyleRules13
    point_rules = get_point_rules(declarations, self.dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1205, in get_point_rules
    and postprocess_symbolizer_image_file(str(values['point-file'].value), dirs)
 \
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1067, in postprocess_symbolizer_image_file
    file_href = urljoin(dirs.source.rstrip('/')+'/', file_href)
AttributeError: Directories instance has no attribute 'source'

======================================================================
ERROR: testStyleRules14 (__main__.StyleRuleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1534, in testStyleRules14
    shield_rule_groups = get_shield_rule_groups(declarations, self.dirs)
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1162, in get_shield_rule_groups
    and postprocess_symbolizer_image_file(str(values['shield-file'].value), dirs
) \
  File "C:\Documents and Settings\xp_user\Desktop\Cascadenik\cascadenik\compile.
py", line 1067, in postprocess_symbolizer_image_file
    file_href = urljoin(dirs.source.rstrip('/')+'/', file_href)
AttributeError: Directories instance has no attribute 'source'

----------------------------------------------------------------------
Ran 160 tests in 12.338s

FAILED (errors=20)

C:\Documents and Settings\xp_user\Desktop\Cascadenik>
</pre>

**Comment by springmeyer** [comment]
after https://github.com/mapnik/Cascadenik/commit/1325e5e89644bfdf4e29ed0c90b3a9e9cdb24a06 we are down to only 12 test failures on windows, of a very different mature, and we've decided that is about all we can do for now as the doc/example.mml all work on windows now...
