### ISSUE TITLE
Python 2.5.1 os x (leopard) test failures with relative-paths branch

### ISSUE THREAD

**Issue by springmeyer** [mapnik/Cascadenik#8]
<pre>
Cascadenik spring$ python test.py 
..................E....
Cascadenik debug: Warning, FontSets will be ignored as they are not yet supported in Mapnik via Python...
.....E..................................FF.F.F...........................................................................................
======================================================================
ERROR: testCompile1 (__main__.CompileXMLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1754, in testCompile1
    cfg = tempfile.NamedTemporaryFile('w', delete=False)
TypeError: NamedTemporaryFile() got an unexpected keyword argument 'delete'

======================================================================
ERROR: testLocalDefaultsFromFile (__main__.DataSourcesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1602, in testLocalDefaultsFromFile
    cfg = tempfile.NamedTemporaryFile('w', delete=False)
TypeError: NamedTemporaryFile() got an unexpected keyword argument 'delete'

======================================================================
FAIL: testLocalLinkedSheetPaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2352, in testLocalLinkedSheetPaths
    assert not os.path.isabs(shp_path)
AssertionError

======================================================================
FAIL: testLocalizedPaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2156, in testLocalizedPaths
    assert not os.path.isabs(img_path)
AssertionError

======================================================================
FAIL: testRelativePaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2228, in testRelativePaths
    assert not os.path.isabs(img_path)
AssertionError

======================================================================
FAIL: testRemotePaths (__main__.RelativePathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 2316, in testRemotePaths
    assert not os.path.isabs(img_path)
AssertionError

----------------------------------------------------------------------
Ran 160 tests in 23.834s

FAILED (failures=4, errors=2)
</pre>

**Comment by springmeyer** [comment]
this has been fixed by adding a py25 relpath implementation
